name: HTML Validator

on: [push, pull_request]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install html-proofer
        run: gem install html-proofer
      - name: Run html-proofer
        run: htmlproofer ./ --only-4xx --check-favicon --check-html